### ISSUE TITLE
host the app online

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [MLH-LHD-Build-2022/Team-Builder#15]
find a way to host the complete app
on vercel or other platforn that will support complete server with backend

**Comment by tusharkhatriofficial** [comment]
I can help you with that!

**Comment by Naresh-chandanbatve** [comment]
@tusharkhatriofficial Go for it.
it uses Nodejs backend and firebase database

**Comment by tusharkhatriofficial** [comment]
and before doing that we need remove the firebase options from the index.js file. I'm opening an issue for that.

**Comment by tusharkhatriofficial** [comment]
Now as we have the dotenv configuration in place the admin can simply create an account on https://www.cyclic.sh/ and can deploy the website with a single click! Please do not forget to add the Environment variables on the hosting platform.

**Comment by Naresh-chandanbatve** [comment]
Done https://elegant-teal-clothes.cyclic.app/

but sessions are not working properly
variable session is showing undefined after redirecting to my click

**Comment by tusharkhatriofficial** [comment]
is it working fine on localhost

**Comment by tusharkhatriofficial** [comment]
After registering I was redirected to the login page and the error occurred when I tried logging in.
<img width="1280" alt="Screenshot 2022-10-16 at 9 54 51 PM" src="https://user-images.githubusercontent.com/64004539/196046695-dd8268f1-735c-42fd-88c6-36923dd58ce7.png">

**Comment by Naresh-chandanbatve** [comment]
try to login again it will work
