### ISSUE TITLE
improve ui of team info page

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [MLH-LHD-Build-2022/Team-Builder#25]

**Comment by Pratik29121** [comment]
assign this issue to me

**Comment by tanitoluwam** [comment]
Hi, i would love to work on this, kindly assign to me

**Comment by Naresh-chandanbatve** [comment]
@tanitoluwam  go for it

**Comment by Naresh-chandanbatve** [comment]
@tanitoluwam  any updates?

**Comment by tanitoluwam** [comment]
Hi, I was a bit occupied over the weekend, I will start working on it right away

**Comment by tanitoluwam** [comment]
I have made a pull request already, kindly review and give your feedback, thanks
